// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2MqcHyEqLYeqG1EtFdz1161Pferac3jY',
    appId: '1:555927879756:web:2736800e397dff0d41b4e9',
    messagingSenderId: '555927879756',
    projectId: 'malay-learner',
    authDomain: 'malay-learner.firebaseapp.com',
    storageBucket: 'malay-learner.firebasestorage.app',
    measurementId: 'G-QYS2V0QJEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUxwq7-QvqMPbq4P0n0hkYwsqKZ5fVZQ',
    appId: '1:555927879756:android:13f7e9b87a71d3c541b4e9',
    messagingSenderId: '555927879756',
    projectId: 'malay-learner',
    storageBucket: 'malay-learner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFeNTjWDxelgLVYXBtgCXmk4dbsldXYw',
    appId: '1:555927879756:ios:af26d98990b3d80341b4e9',
    messagingSenderId: '555927879756',
    projectId: 'malay-learner',
    storageBucket: 'malay-learner.firebasestorage.app',
    iosBundleId: 'com.example.malay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFeNTjWDxelgLVYXBtgCXmk4dbsldXYw',
    appId: '1:555927879756:ios:af26d98990b3d80341b4e9',
    messagingSenderId: '555927879756',
    projectId: 'malay-learner',
    storageBucket: 'malay-learner.firebasestorage.app',
    iosBundleId: 'com.example.malay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2MqcHyEqLYeqG1EtFdz1161Pferac3jY',
    appId: '1:555927879756:web:307595ae2814c2d241b4e9',
    messagingSenderId: '555927879756',
    projectId: 'malay-learner',
    authDomain: 'malay-learner.firebaseapp.com',
    storageBucket: 'malay-learner.firebasestorage.app',
    measurementId: 'G-7657610C20',
  );
}
